-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
-- This uses the async cache to accelerate the prompt construction.
-- There's also the require('vectorcode').query API, which provides
-- more up-to-date information, but at the cost of blocking the main UI.
-- local vectorcode_cacher = require("vectorcode.cacher")
-- vim.schedule(function()
--   vim.api.nvim_create_autocmd("LspAttach", {
--     callback = function()
--       local bufnr = vim.api.nvim_get_current_buf()
--       vectorcode_cacher.async_check("config", function()
--         vectorcode_cacher.register_buffer(bufnr, {
--           n_query = 10,
--         })
--       end, nil)
--     end,
--     desc = "Register buffer for VectorCode",
--   })
-- end)
--
-- local cacher = require("vectorcode.cacher")
--
-- vim.api.nvim_create_autocmd("LspAttach", {
--   callback = function()
--     local bufnr = vim.api.nvim_get_current_buf()
--     cacher.async_check("config", function()
--       cacher.register_buffer(bufnr, {
--         n_query = 10,
--       })
--     end, nil)
--   end,
--   desc = "Register buffer for VectorCode",
-- })
